--------------------------------------------------------
-- Archivo creado  - miércoles-septiembre-10-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APPOINTMENTS
--------------------------------------------------------

  CREATE TABLE "CLINICA_ORACLE"."APPOINTMENTS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"APPOINTMENT_DATE" DATE, 
	"REASON" CHAR(200 BYTE), 
	"PATIENT_ID" NUMBER, 
	"DOCTOR_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DIAGNOSES
--------------------------------------------------------

  CREATE TABLE "CLINICA_ORACLE"."DIAGNOSES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIPTION" CHAR(200 BYTE), 
	"PATIENT_ID" NUMBER, 
	"APPOINTMENT_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOCTORS
--------------------------------------------------------

  CREATE TABLE "CLINICA_ORACLE"."DOCTORS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" CHAR(50 BYTE), 
	"LAST_NAME" CHAR(80 BYTE), 
	"TELEPHONE" CHAR(20 BYTE), 
	"EMAIL" CHAR(100 BYTE), 
	"SPECIALTY_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEDICINES
--------------------------------------------------------

  CREATE TABLE "CLINICA_ORACLE"."MEDICINES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" CHAR(80 BYTE), 
	"PRESENTATION" CHAR(50 BYTE), 
	"DOSE" CHAR(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PATIENTS
--------------------------------------------------------

  CREATE TABLE "CLINICA_ORACLE"."PATIENTS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" CHAR(50 BYTE), 
	"LAST_NAME" CHAR(80 BYTE), 
	"BIRTH_DATE" DATE, 
	"GENDER" CHAR(50 BYTE), 
	"ADDRESS" CHAR(40 BYTE), 
	"TELEPHONE" CHAR(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAYMENTS
--------------------------------------------------------

  CREATE TABLE "CLINICA_ORACLE"."PAYMENTS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PAYMENT_DATE" DATE, 
	"AMOUNT" NUMBER(10,2), 
	"APPOINTMENT_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRESCRIPTIONS
--------------------------------------------------------

  CREATE TABLE "CLINICA_ORACLE"."PRESCRIPTIONS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PRESCRIPTION_DATE" DATE, 
	"APPOINTMENT_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROCEDURES
--------------------------------------------------------

  CREATE TABLE "CLINICA_ORACLE"."PROCEDURES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIPTION" CHAR(200 BYTE), 
	"APPOINTMENT_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECIPE_DETAILS
--------------------------------------------------------

  CREATE TABLE "CLINICA_ORACLE"."RECIPE_DETAILS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"AMOUNT" NUMBER, 
	"INDICATIONS" CHAR(200 BYTE), 
	"PRESCRIPTION_ID" NUMBER, 
	"MEDICINE_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SPECIALTIES
--------------------------------------------------------

  CREATE TABLE "CLINICA_ORACLE"."SPECIALTIES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME_SPECIALTY" CHAR(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into CLINICA_ORACLE.APPOINTMENTS
SET DEFINE OFF;
REM INSERTING into CLINICA_ORACLE.DIAGNOSES
SET DEFINE OFF;
REM INSERTING into CLINICA_ORACLE.DOCTORS
SET DEFINE OFF;
REM INSERTING into CLINICA_ORACLE.MEDICINES
SET DEFINE OFF;
REM INSERTING into CLINICA_ORACLE.PATIENTS
SET DEFINE OFF;
REM INSERTING into CLINICA_ORACLE.PAYMENTS
SET DEFINE OFF;
REM INSERTING into CLINICA_ORACLE.PRESCRIPTIONS
SET DEFINE OFF;
REM INSERTING into CLINICA_ORACLE.PROCEDURES
SET DEFINE OFF;
REM INSERTING into CLINICA_ORACLE.RECIPE_DETAILS
SET DEFINE OFF;
REM INSERTING into CLINICA_ORACLE.SPECIALTIES
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table DOCTORS
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."DOCTORS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."DOCTORS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."DOCTORS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."DOCTORS" MODIFY ("TELEPHONE" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."DOCTORS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."DOCTORS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEDICINES
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."MEDICINES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."MEDICINES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."MEDICINES" MODIFY ("PRESENTATION" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."MEDICINES" MODIFY ("DOSE" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."MEDICINES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SPECIALTIES
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."SPECIALTIES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."SPECIALTIES" MODIFY ("NAME_SPECIALTY" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."SPECIALTIES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table APPOINTMENTS
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."APPOINTMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."APPOINTMENTS" MODIFY ("APPOINTMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."APPOINTMENTS" MODIFY ("REASON" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."APPOINTMENTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRESCRIPTIONS
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."PRESCRIPTIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."PRESCRIPTIONS" MODIFY ("PRESCRIPTION_DATE" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."PRESCRIPTIONS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENTS
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."PAYMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."PAYMENTS" MODIFY ("PAYMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."PAYMENTS" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."PAYMENTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CLINICA_ORACLE"."PAYMENTS" ADD UNIQUE ("APPOINTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DIAGNOSES
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."DIAGNOSES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."DIAGNOSES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."DIAGNOSES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROCEDURES
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."PROCEDURES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."PROCEDURES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."PROCEDURES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RECIPE_DETAILS
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."RECIPE_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."RECIPE_DETAILS" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."RECIPE_DETAILS" MODIFY ("INDICATIONS" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."RECIPE_DETAILS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PATIENTS
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."PATIENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."PATIENTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."PATIENTS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."PATIENTS" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."PATIENTS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."PATIENTS" MODIFY ("TELEPHONE" NOT NULL ENABLE);
  ALTER TABLE "CLINICA_ORACLE"."PATIENTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APPOINTMENTS
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."APPOINTMENTS" ADD FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "CLINICA_ORACLE"."PATIENTS" ("ID") ENABLE;
  ALTER TABLE "CLINICA_ORACLE"."APPOINTMENTS" ADD FOREIGN KEY ("DOCTOR_ID")
	  REFERENCES "CLINICA_ORACLE"."DOCTORS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DIAGNOSES
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."DIAGNOSES" ADD FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "CLINICA_ORACLE"."PATIENTS" ("ID") ENABLE;
  ALTER TABLE "CLINICA_ORACLE"."DIAGNOSES" ADD FOREIGN KEY ("APPOINTMENT_ID")
	  REFERENCES "CLINICA_ORACLE"."APPOINTMENTS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOCTORS
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."DOCTORS" ADD FOREIGN KEY ("SPECIALTY_ID")
	  REFERENCES "CLINICA_ORACLE"."SPECIALTIES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENTS
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."PAYMENTS" ADD FOREIGN KEY ("APPOINTMENT_ID")
	  REFERENCES "CLINICA_ORACLE"."APPOINTMENTS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRESCRIPTIONS
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."PRESCRIPTIONS" ADD FOREIGN KEY ("APPOINTMENT_ID")
	  REFERENCES "CLINICA_ORACLE"."APPOINTMENTS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROCEDURES
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."PROCEDURES" ADD FOREIGN KEY ("APPOINTMENT_ID")
	  REFERENCES "CLINICA_ORACLE"."APPOINTMENTS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECIPE_DETAILS
--------------------------------------------------------

  ALTER TABLE "CLINICA_ORACLE"."RECIPE_DETAILS" ADD FOREIGN KEY ("PRESCRIPTION_ID")
	  REFERENCES "CLINICA_ORACLE"."PRESCRIPTIONS" ("ID") ENABLE;
  ALTER TABLE "CLINICA_ORACLE"."RECIPE_DETAILS" ADD FOREIGN KEY ("MEDICINE_ID")
	  REFERENCES "CLINICA_ORACLE"."MEDICINES" ("ID") ENABLE;
